name: ipa_ip
description: "ITパスポート試験対策アプリ"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  engine:
    path: ../../engine
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - contents/base.json
    - contents/lessons/
    - contents/exercises/
    - contents/anki/
